services:
  - type: web
    name: creator-suite-dev
    env: static
    buildCommand: ""
    # COMMANDE CORRIGÉE : J'ai retiré le "-s" d'ici
    startCommand: "npx serve -l $PORT"
    envVars:
      - key: NODE_ENV
        value: development
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
