services:
  - type: web
    name: creator-suite-dev
    # 1. DOIT être 'node' pour exécuter des scripts
    env: node
    nodeVersion: "18"
    
    # 2. DOIT avoir une buildCommand pour injecter les clés
    buildCommand: "yarn install && yarn run build"
    
    # 3. DOIT être 'yarn start' pour lancer ton script
    startCommand: "yarn start"
    
    envVars:
      - key: NODE_ENV
        value: development
      
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
