services:
  - type: web
    name: InfluIAV1 # Ou le nom que tu as choisi
    env: node # On garde node pour utiliser 'serve'
    plan: free # Important pour le $PORT
    buildCommand: "yarn install" # Juste installer 'serve'
    startCommand: "yarn start" # Lance le script 'start' de package.json
    envVars:
      - key: NODE_ENV
        value: development
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
