services:
  - type: web
    name: creator-suite-dev
    # 1. On dit que c'sest un service "node"
    env: node
    nodeVersion: "18"
    
    # 2. On dit à Render comment "builder" le site
    #    Il va installer les dépendances PUIS lancer le script "build"
    buildCommand: "yarn install && yarn run build"
    
    # 3. On dit à Render comment lancer le site (il utilise le script "start" de package.json)
    startCommand: "yarn start"
    
    envVars:
      # Render lira automatiquement tes variables (SUPABASE_URL, etc.)
      - key: NODE_ENV
        value: development
      
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
